final.exe: main.o binarytree.o
	gcc main.o binarytree.o -0 final.exe

main.o: main.c binarytree.h
	gcc -Wall -c main.c
	
binarytree.o: binarytree.c binarytree.h
	gcc -Wall - c binarytree.c

clean:
	rm *.o final.exe
	ls